version: "3.9"

services:
  redis:
    container_name: redislocal
    hostname: redislocal
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
        - local_redis_data:/data
    restart:
      unless-stopped

  postgres:
    container_name: ppostgres.OpenAI
    image: "postgres:15-alpine"
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "127.0.0.1:8764:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ubnfhf
      POSTGRES_DB: OpenAI_db
    volumes:
      - "ppostgres.postgres.data:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: OpenAI_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: miha@mial.ru
      PGADMIN_DEFAULT_PASSWORD: ubnfhf
    ports:
      - "5055:80"
    depends_on:
      - postgres

volumes:
  ppostgres.postgres.data: {}
  local_redis_data: {}